public enum OrderStatus
{
    PENDING_PAYMENT, 
    PAID,          
    PROCESSING,      
    SHIPPED,         
    DELIVERED,       
    CANCELLED, 
    PROCESSED,     
    REFUNDED,        
    FAILED,
    PENDING_DELIVERY,
    COMPLETED,
    CONFIRMED,
    RETURNED,
    RETURNING,
    RETURN_ACCEPTED,
    NOTDONE,
    DONE,
    REPORTED
}