name: Build and Deploy .NET Application to Plesk via FTP

on:
  push:
    branches:
      - main # Thay đổi nhánh nếu cần

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy mã nguồn từ repository.
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Cài đặt .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Thay đổi phiên bản .NET nếu cần

    # 3. Build dự án .NET và tạo tài liệu Swagger XML
    - name: Build project
      run: dotnet publish -c Release -o ./publish /p:DocumentationFile=./publish/FTSS_API.xml

    # 4. Triển khai mã nguồn qua FTP
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
            server: ${{ secrets.FTP_HOST }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            secure: true  # Enable FTPS
            local-dir: ./publish
            server-dir: / # Thư mục đích trên server
        
