name: Build and Deploy .NET Application to Plesk via FTP

on:
  push:
    branches:
      - main # Thay đổi nhánh nếu cần

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy mã nguồn từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài đặt .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 # Thay đổi phiên bản .NET nếu cần

      # 3. Build dự án .NET và tạo tài liệu Swagger XML
      - name: Build project
        run: dotnet publish -c Release -o ./publish /p:DocumentationFile=./publish/FTSS_API.xml

      # 4. Nén thư mục publish để giảm số lượng file cần truyền
      - name: Compress publish folder
        run: |
          cd publish
          tar -czf ../publish.tar.gz .
          cd ..

      # 5. Kiểm tra kết nối FTP trước khi tải lên
      - name: Check FTP connection
        run: |
          echo "Checking FTP connection..."
          sudo apt-get install -y lftp
          lftp -e "open ${{ secrets.FTP_HOST }}; user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; ls; exit" || echo "FTP connection test completed"

      # 6. Tải lên file nén bằng LFTP (công cụ FTP mạnh mẽ hơn với tính năng tự động thử lại)
      - name: Upload archive using LFTP
        run: |
          sudo apt-get install -y lftp
          lftp -e "set net:max-retries 5; set net:reconnect-interval-base 5; set net:reconnect-interval-multiplier 1; open ${{ secrets.FTP_HOST }}; user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; cd /ftss.id.vn/; put -O . publish.tar.gz; exit"
        
      # 7. Giải nén từ xa trên server (nếu server hỗ trợ SSH)
      # Nếu không có quyền truy cập SSH, bạn có thể cần tải lên từng file riêng lẻ thay vì sử dụng phương pháp nén
      - name: Deploy via FTP (backup method if LFTP fails)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /ftss.id.vn/
          exclude: |
            **/*.pdb
            **/*.config
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose
          timeout: 300000  # Tăng timeout lên 5 phút
          retries: 5       # Tăng số lần thử lại
          protocol: ftp    # Có thể thử ftps nếu server hỗ trợ
