name: Build and Deploy .NET Application to Plesk via FTP

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy mã nguồn từ repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Liệt kê nội dung thư mục để kiểm tra
    - name: List current directory
      run: ls -R

    # 3. Cài đặt .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # 4. Restore dependencies
    - name: Restore dependencies
      run: dotnet restore FTSS-BE/FTSS/FTSS.sln

    

    # 6. Build dự án .NET
    - name: Build project
      run: dotnet publish FTSS-BE/FTSS/FTSS.csproj -c Release -o ./publish

    # 7. Triển khai mã nguồn qua FTP
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
         server: ${{ secrets.FTP_HOST }}
         username: ${{ secrets.FTP_USERNAME }}
         password: ${{ secrets.FTP_PASSWORD }}
         local-dir: ./publish/
         server-dir: ${{ secrets.FTP_TARGET_DIR }}
         exclude: |
          **/*.pdb
          **/*.config
         log-level: verbose
