name: Build and Deploy .NET Application to Windows VPS via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Lấy mã nguồn từ repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài đặt .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # 3. Build dự án .NET và tạo tài liệu Swagger XML
      - name: Build project
        run: dotnet publish -c Release -o ./publish /p:DocumentationFile=./publish/FTSS_API.xml

      # 4. Triển khai mã nguồn qua FTP vào thư mục tạm
      - name: Deploy to staging via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 14.225.220.28
          username: ftss-server
          password: ftss12345
          local-dir: ./publish/
          server-dir: /staging/
          protocol: ftp
          dry-run: false
          log-level: verbose
