name: Build and Deploy .NET Application to Plesk via FTP

on:
  push:
    branches:
      - main # Thay đổi nhánh nếu cần

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Lấy mã nguồn từ repository.
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Cài đặt .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Thay đổi phiên bản .NET nếu cần

    # 3. Build dự án .NET và tạo tài liệu Swagger XML
    - name: Build project
      run: dotnet publish -c Release -o ./publish /p:DocumentationFile=./publish/FTSS_API.xml

    # 4. Triển khai mã nguồn qua FTP với retry
    - name: Deploy via FTP
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10 # Thời gian tối đa cho mỗi lần thử (tùy chọn)
        max_attempts: 3 # Thử lại tối đa 3 lần
        retry_wait_seconds: 30 # Chờ 30 giây giữa các lần thử
        command: |
          npx -y ftp-deploy --server ${{ secrets.FTP_HOST }} \
            --username ${{ secrets.FTP_USERNAME }} \
            --password ${{ secrets.FTP_PASSWORD }} \
            --local-dir ./publish/ \
            --server-dir /ftss.id.vn/ \
            --exclude "**/*.pdb" "**/*.config" \
            --log-level verbose
